"""empty message

Revision ID: 9bcab7b32efd
Revises: cafa750034b0
Create Date: 2021-07-11 16:23:59.689928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcab7b32efd'
down_revision = 'cafa750034b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Custom execute command
    op.execute('UPDATE todos SET completed=False WHERE completed IS NULL;')

    # Custom update command
    op.alter_column('todos', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
